//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cafe.Common.Resources.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit cannot be greater than the price.
        /// </summary>
        internal static string deposite_cannot_gratter_than_price {
            get {
                return ResourceManager.GetString("deposite_cannot_gratter_than_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the shift first before starting.
        /// </summary>
        internal static string error_start_shift_first {
            get {
                return ResourceManager.GetString("error_start_shift_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, please try again later.
        /// </summary>
        internal static string error_try_again_later {
            get {
                return ResourceManager.GetString("error_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please try again later.
        /// </summary>
        internal static string error_try_later {
            get {
                return ResourceManager.GetString("error_try_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found.
        /// </summary>
        internal static string event_not_found {
            get {
                return ResourceManager.GetString("event_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string invalid_password {
            get {
                return ResourceManager.GetString("invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        internal static string invalid_user_name {
            get {
                return ResourceManager.GetString("invalid_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current active shift.
        /// </summary>
        internal static string no_current_active_shift {
            get {
                return ResourceManager.GetString("no_current_active_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add order items.
        /// </summary>
        internal static string please_add_order_items {
            get {
                return ResourceManager.GetString("please_add_order_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the current shift first.
        /// </summary>
        internal static string please_close_current_shift_first {
            get {
                return ResourceManager.GetString("please_close_current_shift_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserving past dates is not allowed.
        /// </summary>
        internal static string reserve_past_date_not_allowed {
            get {
                return ResourceManager.GetString("reserve_past_date_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table already has an active order.
        /// </summary>
        internal static string the_table_alerdy_has_active_order {
            get {
                return ResourceManager.GetString("the_table_alerdy_has_active_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Not Found.
        /// </summary>
        internal static string token_not_found {
            get {
                return ResourceManager.GetString("token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Exists.
        /// </summary>
        internal static string user_already_exists {
            get {
                return ResourceManager.GetString("user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfully.
        /// </summary>
        internal static string user_created_success_fully {
            get {
                return ResourceManager.GetString("user_created_success_fully", resourceCulture);
            }
        }
    }
}
