//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cafe.Common.Resources.SharedResource.ar", typeof(SharedResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيداع لا يمكن أن يكون أكبر من السعر.
        /// </summary>
        internal static string deposite_cannot_gratter_than_price {
            get {
                return ResourceManager.GetString("deposite_cannot_gratter_than_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ الوردية أولاً قبل البدء.
        /// </summary>
        internal static string error_start_shift_first {
            get {
                return ResourceManager.GetString("error_start_shift_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ، يرجى المحاولة مرة أخرى لاحقًا.
        /// </summary>
        internal static string error_try_again_later {
            get {
                return ResourceManager.GetString("error_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ، يرجى المحاولة لاحقًا.
        /// </summary>
        internal static string error_try_later {
            get {
                return ResourceManager.GetString("error_try_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث غير موجود.
        /// </summary>
        internal static string event_not_found {
            get {
                return ResourceManager.GetString("event_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صالحة.
        /// </summary>
        internal static string invalid_password {
            get {
                return ResourceManager.GetString("invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم غير صالح.
        /// </summary>
        internal static string invalid_user_name {
            get {
                return ResourceManager.GetString("invalid_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تحويل نشط حاليًا.
        /// </summary>
        internal static string no_current_active_shift {
            get {
                return ResourceManager.GetString("no_current_active_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة عناصر الطلب.
        /// </summary>
        internal static string please_add_order_items {
            get {
                return ResourceManager.GetString("please_add_order_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إغلاق الوردية الحالية أولاً.
        /// </summary>
        internal static string please_close_current_shift_first {
            get {
                return ResourceManager.GetString("please_close_current_shift_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بحجز التواريخ السابقة.
        /// </summary>
        internal static string reserve_past_date_not_allowed {
            get {
                return ResourceManager.GetString("reserve_past_date_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطاولة تحتوي بالفعل على طلب نشط.
        /// </summary>
        internal static string the_table_alerdy_has_active_order {
            get {
                return ResourceManager.GetString("the_table_alerdy_has_active_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز غير موجود.
        /// </summary>
        internal static string token_not_found {
            get {
                return ResourceManager.GetString("token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم موجود بالفعل.
        /// </summary>
        internal static string user_already_exists {
            get {
                return ResourceManager.GetString("user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء المستخدم بنجاح.
        /// </summary>
        internal static string user_created_success_fully {
            get {
                return ResourceManager.GetString("user_created_success_fully", resourceCulture);
            }
        }
    }
}
